### ISSUE TITLE
Add casa logging to pipeline log file

### ISSUE THREAD

**Issue by varenius** [e-merlin/CASA_eMERLIN_pipeline#49]
Currently the casa output is not appended to the pipeline logfile. This can be fixed in two ways (as described at the page https://casa.nrao.edu/casadocs/casa-5.1.0/usingcasa/casa-logger)
1) Run CASA with "casa --logfile otherfile.log", but this makes this the responsibility of the user and it's not nice. Instead one should:
2) modify the pipeline to make CASA use the pipeline logfile. Quick hardcoded fix is to include the line 
`casalog.setlogfile('eMCP.log')` in the file `eMERLIN_CASA_pipeline.py` after initialising the logger, i.e. at line 30 somewhere around the current command `logger.addHandler(consoleHandler)`.

**Comment by jmoldon** [comment]
Sounds good. Thanks for finding the right way to do it.

I prefer to keep the pipeline log separated from the CASA log. Just because the pipeline log produces reduced information on what is set in the pipeline (only which tasks are run and the key parameters of them), while the CASA log has much more information and details, which is good to have available, but more difficult to browse. So I suggest using the `casalog.setlogfile` command and put the content on a CASA_<date>.log file.

Also, this is a different discussion, I always wanted a way to extract the actual commands in the CASA log, to quickly see what CASA executed. In the long term my idea is to translate the eMCP.log txt file to a weblog, from which you can link to the actual casa command that was executed (and maybe the full output for that particular task). We can discuss that later when thinking on the weblog itself.

**Comment by jmoldon** [comment]
Solved by #54
