### ISSUE TITLE
Overlapping text in caltable plots

### ISSUE THREAD

**Issue by varenius** [e-merlin/CASA_eMERLIN_pipeline#77]
The caltable plots are very nice. The only issue I find is that the title text on the panels sometimes is too long, perhaps that depends on the project filename. Anyway, it would be nice to break it into multiple lines to avoid overlapping. Now it is sometimes hard to see which antenna a plot refers to. See attacehed example:
<img width="998" alt="screen shot 2017-11-08 at 12 19 28" src="https://user-images.githubusercontent.com/8872291/32548889-47cc3a66-c47f-11e7-9882-6605bf5a837c.png">

**Comment by jmoldon** [comment]
Yes, those are old plots. Now I use plotms to plot calibration tables:

![egj_3c264_l1_bpcal_p g0_phs](https://user-images.githubusercontent.com/1053066/32549899-048c855e-c483-11e7-866a-87df6552683a.png)

Copied from #76:

I recommend you use the new v0.6.3 updated yesterday. It produces much better plots of the calibration tables using plotms instead of plotcal, which is quite terrible. It will also put a lot of information on the calibration steps and those plots in a new tab in the weblog. If you started with v0.6.2, remove all the pkl files in the main forlder and in ./calib/ before running newer versions, because there are a few additions to those pickle files that the weblog needs. And of course, to have the new calibration plots you will need to run the corresponding calibration steps again.

**Comment by jmoldon** [comment]
Improved in b7a13d23402947b3276ce0e8173b4a881060984f
